<a href="https://colab.research.google.com/github/zoegracecolsenet/Docs/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np


#### 2. Print your NumPy version.

In [2]:
print(np.__version__)


2.0.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.random((2, 3, 5))


In [5]:
a = np.random.rand(2, 3, 5)


In [6]:
a = np.random.uniform(size=(2, 3, 5))


#### 4. Print *a*.


In [7]:
print(a)


[[[0.77456792 0.33269296 0.85967336 0.13703487 0.82281319]
  [0.81759003 0.75884053 0.27817612 0.58007685 0.554631  ]
  [0.94853199 0.18332828 0.32591976 0.88602769 0.70086243]]

 [[0.43653687 0.81992114 0.53298727 0.26664651 0.63991991]
  [0.67140536 0.18588192 0.77555483 0.76991521 0.95311761]
  [0.83167692 0.12345876 0.04676666 0.04473732 0.47978509]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
b = np.ones((5, 2, 3))


#### 6. Print *b*.


In [9]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
print(a.size == b.size)


True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
# No, because the operands could not be broadcast together
try:
    result = a + b
except ValueError as e:
    print("Cannot add a and b:", e)


Cannot add a and b: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [14]:
c = b.transpose(1, 2, 0)  # from (5, 2, 3) to (2, 3, 5)
print(c.shape)


(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [33]:
d = a + c
print(d)
# because their shapes are the same


[[[1.77456792 1.33269296 1.85967336 1.13703487 1.82281319]
  [1.81759003 1.75884053 1.27817612 1.58007685 1.554631  ]
  [1.94853199 1.18332828 1.32591976 1.88602769 1.70086243]]

 [[1.43653687 1.81992114 1.53298727 1.26664651 1.63991991]
  [1.67140536 1.18588192 1.77555483 1.76991521 1.95311761]
  [1.83167692 1.12345876 1.04676666 1.04473732 1.47978509]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [17]:
print("a:\n", a)
print("d:\n", d)
# all the elements in d is greater than in a


a:
 [[[0.77456792 0.33269296 0.85967336 0.13703487 0.82281319]
  [0.81759003 0.75884053 0.27817612 0.58007685 0.554631  ]
  [0.94853199 0.18332828 0.32591976 0.88602769 0.70086243]]

 [[0.43653687 0.81992114 0.53298727 0.26664651 0.63991991]
  [0.67140536 0.18588192 0.77555483 0.76991521 0.95311761]
  [0.83167692 0.12345876 0.04676666 0.04473732 0.47978509]]]
d:
 [[[1.77456792 1.33269296 1.85967336 1.13703487 1.82281319]
  [1.81759003 1.75884053 1.27817612 1.58007685 1.554631  ]
  [1.94853199 1.18332828 1.32591976 1.88602769 1.70086243]]

 [[1.43653687 1.81992114 1.53298727 1.26664651 1.63991991]
  [1.67140536 1.18588192 1.77555483 1.76991521 1.95311761]
  [1.83167692 1.12345876 1.04676666 1.04473732 1.47978509]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
e = a * c
print(e)


[[[0.77456792 0.33269296 0.85967336 0.13703487 0.82281319]
  [0.81759003 0.75884053 0.27817612 0.58007685 0.554631  ]
  [0.94853199 0.18332828 0.32591976 0.88602769 0.70086243]]

 [[0.43653687 0.81992114 0.53298727 0.26664651 0.63991991]
  [0.67140536 0.18588192 0.77555483 0.76991521 0.95311761]
  [0.83167692 0.12345876 0.04676666 0.04473732 0.47978509]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [20]:
print(np.array_equal(e, a))  # yes because it is multiplied by one


True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [22]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("max:", d_max)
print("min:", d_min)
print("mean:", d_mean)


max: 1.9531176117410254
min: 1.0447373166926153
mean: 1.55130261193876


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [24]:
f = np.empty_like(d)


#### 16. Populate the values in *f*.

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [25]:
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [26]:
print("d:\n", d)
print("f:\n", f)


d:
 [[[1.77456792 1.33269296 1.85967336 1.13703487 1.82281319]
  [1.81759003 1.75884053 1.27817612 1.58007685 1.554631  ]
  [1.94853199 1.18332828 1.32591976 1.88602769 1.70086243]]

 [[1.43653687 1.81992114 1.53298727 1.26664651 1.63991991]
  [1.67140536 1.18588192 1.77555483 1.76991521 1.95311761]
  [1.83167692 1.12345876 1.04676666 1.04473732 1.47978509]]]
f:
 [[[ 75.  25.  75.  25.  75.]
  [ 75.  75.  25.  75.  75.]
  [ 75.  25.  25.  75.  75.]]

 [[ 25.  75.  25.  25.  75.]
  [ 75.  25.  75.  75. 100.]
  [ 75.  25.  25.   0.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [32]:
fstr = np.empty(d.shape, dtype=object)
fstr[(d > d_min) & (d < d_mean)] = "b"
fstr[(d > d_mean) & (d < d_max)] = "d"
fstr[d == d_mean] = "c"
fstr[d == d_min] = "a"
fstr[d == d_max] = "e"

print(fstr)


[[['d' 'b' 'd' 'b' 'd']
  ['d' 'd' 'b' 'd' 'd']
  ['d' 'b' 'b' 'd' 'd']]

 [['b' 'd' 'b' 'b' 'd']
  ['d' 'b' 'd' 'd' 'e']
  ['d' 'b' 'b' 'a' 'b']]]
